= DDD / CQRS / Event Sourcing avec Axon
Sylvain Maillard <smaillard@oui.sncf>

== L'Event Sourcing

L'event sourcing est un pattern d'architecture dont le principe de base est relativement simple:

* stocker les changements d'état d'un système plutôt que les états eux-mêmes,
* les changements d'état sont des évènements.

=== Stockage des états

Exemple basique hyper classique:

:dummy_user: Mr André Mothé

.un objet Compte bancaire dans une table de compte bancaire.
[source,json]
[subs="attributes"]
----
{
    "numero": 123456,
    "propriétaire": "{dummy_user}",
    "solde": { "valeur":15.0, "devise": "EUR" }
}
----

Si on change le compte bancaire, mettons qu'on lui verse son salaire à {dummy_user}, le solde va évoluer
mais on va perdre trace de l'opération. Il faudra mettre en place une autre entité, par exemple `Opération`.

.un objet Opération dans une table d'audit.
[source,json]
----
{
    "type_operation": "crédit",
    "numero_compte": 123456,
    "montant": { "valeur":100.0, "devise": "EUR" }
}
----

Lorsque l'opération est appliquée, si on regarde le compte bancaire on aura évidement:

.Etat du compte de {dummy_user} après opération.
[source,json]
[subs="attributes"]
----
{
    "numero": 123456,
    "propriétaire": "{dummy_user}",
    "solde": { "valeur":115.0, "devise": "EUR" }
}
----

=== Stockage des évènements (event sourcing)

Dans l'event sourcing, plus besoin ni d'une table de compte bancaire, ni d'une table d'audit.
En fait, on aura uniquement une table des événements.

.Table des événements.
[source,json]
[subs="attributes"]
----
[
{
    "id":0,
    "type_event": "compte_ouvert",
    "numero_compte": 123456,
    "propriétaire": "{dummy_user}",
    "montant": { "valeur":15.0, "devise": "EUR" }
},
{
    "id":1,
    "type_event": "compte_credité",
    "numero_compte": 123456,
    "montant": { "valeur":100.0, "devise": "EUR" }
}
]
----

.Remarque
****
Les événements d'expriment toujours au passé. Ils ont un caractère immuable, car jusqu'à preuve du contraire
on ne peut pas changer le passé. (bon on peut bidouiller les events dans la base mais c'est pas le principe
ok ?)
****

On voit ici que l'ordre est extrêmement important. si j'ai des opérations débit/crédit en désordre,
je risque d'obtenir un montant incorrect pour {dummy_user}.

=== Comment récupérer l'état courant de l'entité "compte"

Avec notre journal d'évent, le principe est de *rejouer* les événements les uns après les autres pour obtenir l'état
actuel du système.

.Etat initial T0
----
{}
----

Application de l'événement avec l'id "0" (ouverture de compte avec 15€ dessus):

.Etat du compte à T1
[source,json]
[subs="attributes"]
----
{
    "numero": 123456,
    "propriétaire": "{dummy_user}",
    "solde": { "valeur":15.0, "devise": "EUR" }
}
----

Application de l'événement avec l'id "1" (crédit de 100€):

.Etat du compte à T2
[source,json]
[subs="attributes"]
----
{
    "numero": 123456,
    "propriétaire": "{dummy_user}",
    "solde": { "valeur":115.0, "devise": "EUR" }
},
----

C'est ce qui va devoir être fait avant de pouvoir appliquer un nouvel événement via une commande.

=== Créer des évents avec des Commandes

On a vu que le stockage des events permet de conserver l'état de l'application en appliquant chaque event
sur l'aggregat associé.

Pour modifier le système (c'est à dire générer les events) on va utiliser des *commandes*.

Une commande est une intention de modification du système / de l'aggregat.
Une commande peut:
 * être refusée,
 * générer un ou plusieurs events,
 * n'avoir aucun effet.

Ce sont les commandes qui gèrent les effets de bord du système (par exemple: communication avec un partenaire)


=== Résumé sur l'event sourcing:

* Cycle:

Commande -> Replay des events pour retrouver l'état
-> execution de la commande sur l'aggregat -> génération de nouveaux events.

Lorsqu'une nouvelle commande arrive, on rééxecute cette chaine.


== Quel rapport avec le DDD ?

L'event sourcing marche pas mal avec le DDD: en effet, l'application de ce pattern oblige à réfléchir en terme
métier et moins en terme "procédural": pas question ici de Api de Helper de Manager etc. On doit rester focus
sur les notions métiers (Compte, Crédit) et donc mettre en oeuvre le `language ubiquitaire` du DDD.

On peut associer les évenements de l'évent sourcing avec les Domain Events du DDD.

=== Quelques précisions sur le DDD

Quand on parle DDD, il faut distinguer deux "sortes" de ddd:

- le DDD stratégique: il s'applique à l'ensemble du SI. Il permet d'identifier des Bounded Context, qui sont des
sortes de modules fonctionnels au sein desquels un mot aura le même sens pour tous les acteurs que ce soit les dev
ou les experts métiers (on parle du langage ubiquitaire).

 Exemple: Dans le cadre d'un parcours de ventes, la "Commande" n'aura pas le même sens si on est en cours de
 finalisation (auquel cas on souhaite avoir tout le détail) ou si on est sur le back office de paiement (auquel
 cas on aura juste l'identifiant de la commande).

- le DDD tactique: c'est une notion qui va s'appliquer sur un seul "Bounded Context", typiquement sur une application
et dans une seule équipe (c'est le plus simple). Le DDD tactique va nous aider à identifier les éléments de base de
l'application, et les définir en respectant le language commun.

Le DDD tactique fourni des briques de base pour la conception de notre application. En utilisant ces briques, on va
avoir un application orientée objets et non pas une application en couche avec des io et du procédural pour tout
tenir en glue.

.Important
****
L'idée du DDD tactique ici est de faire le lien entre le code applicatif et le langage et les concepts manipulés par
le métier.
****

Les éléments clés du DDD tactique qu'on va mettre en oeuvre dans Axon:

- Aggregat
- Entity
- Value Object
- Services ????

== Quel rapport avec le CQRS ?

CQRS signifie `Command / Queries Responsabilities segregation`.

En gros on sépare la lecture de l'écriture. On peut faire du CQRS sans ES et de l'ES sans CQRS.

Par contre il est relativement simple de faire du CQRS avec l'event sourcing, ça ne coûte pas vraiment plus cher.

Avec le système de commande on a déjà la partie "Command" de CQRS.

Pour la partie Query, on va avoir recours à ce qu'on appelle des `projections`. Une projection est une
représentation particulière/une vue d'un aggregat.

Dans notre exemple précédent:

[source,json]
[subs="attributes"]
----
{
    "numero": 123456,
    "propriétaire": "{dummy_user}",
    "solde": { "valeur":115.0, "devise": "EUR" }
},
----

est une projection du compte de {dummy_user}.

La projection est construite en consommant les événements concernant l'aggregat et en les appliquant les uns
après les autres.

Quel intérêt ? on peut ajouter n'importe quelle projection sans modifier le fonctionnement de l'application.

== Récapitulatif

-> TODO ajouter le schéma d'archi Axon. ça fait une transition comme ça.

== Pourquoi Axon ?

[quote,Un article de blog de Xebia sur l'ES]
Vous pouvez (devez) faire sans framework.

Ça c'est un gars qui n'a pas du faire beaucoup d'eventsourcing.
Sur son blog, il indique que les concepts derrière l'event sourcing sont tellement simple qu'il n'est pas
nécessaire d'utiliser un framework.

Dans mon expérience ce n'est pas le cas:

- Sur le *Hub de paiement*, nous avons utilisé l'ES mais avons pas mal galéré (pas de CQRS sur le hub,
  on rejoue pas les events...),
- Sur *hespéride*, le système d'ES est tellement compliqué qu'il a justifié la refonte complète de l'application.

D'où l'intérêt d'utiliser un framework.

== Axon



